config/routes.rb
Rails.application.routes.draw do
  resources :mustdo_lists

  root 'mustdo_lists#index'
  

end

app/models/mustdo_list.rb
class MustdoList < ActiveRecord::Base

	has_many :mustdo_items

	validates :title, presence: true
	validates :title, length: {minimum: 3}
	validates :category, presence: true, inclusion: {in: %w(Restaurants Cafes Books Movies Recipes Activities), message: "'%{value}' is not equal to one of the following: Restaurants, Cafes, Books, Movies, Recipes, or Activities" }
	validates :description, presence: true
	validates :description, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mustdo_lists_controller.rb
class MustdoListsController < ApplicationController
  before_action :set_mustdo_list, only: [:show, :edit, :update, :destroy]

  # GET /mustdo_lists
  # GET /mustdo_lists.json
  def index
    @mustdo_lists = MustdoList.all
  end

  # GET /mustdo_lists/1
  # GET /mustdo_lists/1.json
  def show
  end

  # GET /mustdo_lists/new
  def new
    @mustdo_list = MustdoList.new
  end

  # GET /mustdo_lists/1/edit
  def edit
  end

  # POST /mustdo_lists
  # POST /mustdo_lists.json
  def create
    @mustdo_list = MustdoList.new(mustdo_list_params)

    respond_to do |format|
      if @mustdo_list.save
        format.html { redirect_to @mustdo_list, notice: 'Mustdo list was successfully created.' }
        format.json { render :show, status: :created, location: @mustdo_list }
      else
        format.html { render :new }
        format.json { render json: @mustdo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mustdo_lists/1
  # PATCH/PUT /mustdo_lists/1.json
  def update
    respond_to do |format|
      if @mustdo_list.update(mustdo_list_params)
        format.html { redirect_to @mustdo_list, notice: 'Mustdo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @mustdo_list }
      else
        format.html { render :edit }
        format.json { render json: @mustdo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mustdo_lists/1
  # DELETE /mustdo_lists/1.json
  def destroy
    @mustdo_list.destroy
    respond_to do |format|
      format.html { redirect_to mustdo_lists_url, notice: 'Mustdo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mustdo_list
      @mustdo_list = MustdoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mustdo_list_params
      params.require(:mustdo_list).permit(:title, :category, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mustdo_lists_helper.rb
module MustdoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mustdo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mustdo_lists/_form.html.erb
<%= form_for(@mustdo_list) do |f| %>
  <% if @mustdo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mustdo_list.errors.count, "error") %> prohibited this mustdo_list from being saved:</h2>

      <ul>
      <% @mustdo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mustdo_lists/edit.html.erb
<h1>Editing mustdo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @mustdo_list %> |
<%= link_to 'Back', mustdo_lists_path %>

app/views/mustdo_lists/index.html.erb
<h1>Listing mustdo_lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mustdo_lists.each do |mustdo_list| %>
      <tr id="<%= dom_id(mustdo_list) %>">
        <td><%= mustdo_list.title %></td>
        <td><%= mustdo_list.category %></td>
        <td><%= mustdo_list.description %></td>
        <td><%= link_to 'Show', mustdo_list %></td>
        <td><%= link_to 'Edit', edit_mustdo_list_path(mustdo_list) %></td>
        <td><%= link_to 'Destroy', mustdo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mustdo list', new_mustdo_list_path %>

app/views/mustdo_lists/new.html.erb
<h1>New mustdo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', mustdo_lists_path %>

app/views/mustdo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mustdo_list.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @mustdo_list.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mustdo_list.description %>
</p>

<%= link_to 'Edit', edit_mustdo_list_path(@mustdo_list) %> |
<%= link_to 'Back', mustdo_lists_path %>